services:
  - type: web
    name: challenge-48h-server
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && node dist/main
    envVars:
      - key: NODE_ENV
        value: production
